---
title: "Overlap between Built Environment and Spoiled Product"
author: "Sarah Daly"
date: "September 2024"
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
Purpose:  Determine overlap in built envrionment and spoiled product 

Input:  20240814_genera_database.csv
Fac1_genera.csv
Fac2_genera.csv
Fac3_genera.csv
Output: csv, tif 

#Set working directory
```{r}
setwd("C:/Users/dalys/Box/Microbial Food Safety & Spoilage Lab/Lab Members/Sarah Daly/ITS Methods Project/Github upload/Pie and Bar chart Overlap")

#Load libraries 
library(sjmisc) #Check crossing and nested
library(randtests) #check for randomness
library(car) #regression, correlation
library(MASS) #correlation
library(corrplot) #correlatin plots
library(QuantPsyc) #multivariate normal distrubtion test
library(heplots) #BOX M TEST 
library(GGally) #grouping
library(rstatix) #stats 
library(ROCR) #ROCR plot
library(devtools)
library(vegan) #permanova
#install.packages("ggplot2", dependencies = TRUE)
#install.packages('Rcpp', dependencies = TRUE)
#install.packages("rlang")
library(rlang)
library(ggplot2)
library(lme4) #lmer fuction
require(gridExtra)
library(rstatix)  # https://github.com/kassambara/rstatix
require(gridExtra)
library(ggpubr)
library(scater) #multiplot
```

#Load Data
##https://towardsdatascience.com/doing-and-reporting-your-first-planned-contrasts-in-r-ee77ff#277088
```{r}
list.files()
df<- read.csv("20240814_genera_database.csv")
head(df)
df$Site<- as.factor(df$Site)
df$Genera<- as.factor(df$Genera)


```

#Create Color_vector
```{r}
#I copied and pasted the results of genus_color$cat
#I cannot figure out how to concatenate the columns wtih an equal sign between them
#There are in ABC order so if there is a missing genera just add it manually to this list.
#scale_fill_manual(values=color_col) in the function below 
color_col<- c(

"Alternaria" =          "grey75" ,
 "Apiotrichum" =           "grey75"  ,     
 "Aspergillus" =           "grey75" ,    
"Aureobasidium" =             "peachpuff"  ,   
"Botryotinia" = "lemonchiffon",
"Bullera" = "aliceblue",
"Candida"  =        "red",
"Chordomyces" =           "grey75" ,
"Cladosporium" =            "darkgreen" ,  ##FIXX###
 "Clavispora" =          "rosybrown" ,
  "Cutaneotrichosporon" =                   "grey75",          
 "Cyberlindnera" =             "mistyrose2" ,  
"Cyphellophora" =             "mintcream"   , 
"Cystobasidium" =             "white"    ,    
"Cystofilobasidium" =                 "gold2"    ,         
 "Debaryomyces"   =              "grey75",
"Dictyosporiaceae_gen_Incertae_sedis" = "darkolivegreen1"        ,            
"Didymella" =         "grey75"  ,
"Didymellaceae_g__" =                 "hotpink"   ,      
 "Exophiala"  = "grey75",
 "Filobasidium" =            "plum" ,       
"Fusarium" =        "grey75",
 "Fusicolla" =         "cornsilk2",
 "Geotrichum" =          "purple4"  , 
 "Galactomyces" = "darksalmon",
 "Geotrichum/Galactomyces" = "seagreen",
 "Hanseniaspora (Kloechera)"= "violetred",
 "Humicola"   =          "indianred3",
 "Iodophanus" =          "slateblue4",
 "Kluyveromyces" =             "cadetblue" ,   
 "Knufia" =      "wheat2",
 "Kurtzmaniella" =             "olivedrab1" ,  
"Leucosporidium" =              "yellowgreen",   
 "Malassezia" =         "lightpink4",
"Meyerozyma" =         "violetred4",
 "Mrakia" =     "sienna",
 "Mucor"      =  "dodgerblue3",
"Naganishia"  =   "grey75",
"Neoascochyta" = "lightpink2",
"None" = "grey4",
"Paecilomyces" = "ivory",
 "Ophiostoma" =          "seashell4" ,
"Orbilia" =      "gold"   ,
"Other" =      "grey38"   ,
 "Papiliotrema"   =              "mediumseagreen",
 "Penicillium " =          "springgreen" ,
 "Penicillium" =          "springgreen" ,
"Phlebiopsis"  =            "springgreen2",
 "Pichia" =      "navy",
 "Piskurozyma" =           "firebrick1" ,
 "Preussia"   =          "violetred2",
 "Proceropycnis" =             "seashell2",    
 "Rhodosporidiobolus" =                  "thistle4",
  "Rhizopus" = "grey75",
"Rhodotorula" =           "grey16",     
 "Rozellomycota_gen_Incertae_sedis" = "lemonchiffon",                    
 "Saccharomyces"  =              "paleturquoise1",
"Saccharomycetales_fam_Incertae_sedis_g__" = "grey50",  
"Sarocladium" = "grey75",
  "Sporobolomyces" = "lemonchiffon2",
"Symmetrospora"  =             "lightgoldenrod",
 "Talaromyces" =           "violet",     
"Tausonia"    =           "dodgerblue1",
 "Tetracladium" =            "ivory2",   
 "Torulaspora" =           "slateblue1", 
"Trichoderma" =           "grey80",     
"Trichosporon" =           "forestgreen",
"Trametes" = "grey68",
"Vishniacozyma" =             "grey75",   
  "Yarrowia"   =          "violet")

#In your GGPLOt code use this line to get consistant colors between barcharts:  
#scale_fill_manual(values=color_col)

```

#Get unique combos of factors
```{r}
write.csv(unique(df$Genera), "Unique_genera.csv")
```


#Pie Chart
```{r}
#Get the number of data points for Factors
#Groups to Plot 
#Filter each sample
#name is string

piechat<- function(fac, name){
df<- read.csv("20240814_genera_database.csv")
head(df)
df$Site<- as.factor(df$Site)
df$Genera<- as.character(df$Genera)

target <- c(fac)
df_f=filter(df,(df$Site %in% target) )  #remove 0 rows
head(df_f)
target <- c("None")
df_f=filter(df_f,!(df_f$Genera %in% target) )  #remove 0 rows


head(df_f)

per<- df_f %>% group_by(Genera) %>%
  summarise(n = n()) 
head(per)

df_f<- as.data.frame(per)


df_f

#consildiate "other rows
df_f<- aggregate(n ~ Genera, data =df_f, FUN = sum)

df_f <- df_f  %>% mutate(freq = paste0(round(n / sum(n) * 100, 0), "%"))
head(df_f)

write.csv(per, paste(name,"Percent Genera.csv"))


df_f

head(df_f)

#Replacd low freq with other
i = 1
while (i<= dim(df_f)[1]){

  if (df_f$freq[i] %in% c("1%", "2%", "3%", "4%")){print('yes') 
   df_f$Genera[i] <- 'Other'}
  else(print('no'))
  i = i+1
}

df_f

#change freq label
df_f <- df_f  %>% mutate(freq_num = (n / sum(n) * 100))
df_f

df_f<- df_f[,c(1:2,4)]
df_f

df_f<- df_f %>%
  group_by(Genera) %>%
    summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE)))


df_f <- df_f  %>% mutate(freq = paste0(round(freq_num, 0), "%"))

df_f
##ggplot
#https://r-charts.com/part-whole/pie-chart-ggplot2/ 
p<- ggplot(df_f, aes(x = "", y = n, fill = Genera)) +
  geom_col(color = NA) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), #Remove background
panel.background = element_blank(), axis.line = element_line(colour = "white"))+
    geom_text(aes(label = freq),
            position = position_stack(vjust = 0.5),  size=12) +
     scale_fill_manual(values=color_col)+
  coord_polar(theta = "y")+theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.background = element_rect(fill = "white"),
        legend.background = element_rect(fill = "white"))+
  theme(legend.text=element_text(size=18), legend.title=element_blank())

print(p)
tiff(paste(name, "Percent_other_overlap.tif", sep=" "), res=300, compression = "lzw", height=9, width=15, units="in")
print(p)
dev.off()

pdf(paste(name, "Percent_other_overlap.pdf", sep=" "), height=9, width=15)
print(p)
dev.off()

}

#############################

piechat("Facility3", "Facility3")
piechat("Facility1", "Facility1")
piechat("Facility2", "Facility2")
```


#Barplot
```{r}
#Facility 1
fac1<- read.csv("Fac1_genera.csv")
head(fac1)
class(fac1$Relative.Abundance)
fac1$Genera<- as.factor(fac1$Genera)
fac1$Relative.Abundance<- as.numeric(fac1$Relative.Abundance)*100
fac1

#custo color
color_col<- c(

"Alternaria" =          "grey75" ,
 "Apiotrichum" =           "grey75"  ,     
 "Aspergillus" =           "grey75" ,    
"Aureobasidium" =             "peachpuff"  ,   
"Botryotinia" = "lemonchiffon",
"Bullera" = "aliceblue",
"Candida"  =        "red",
"Chordomyces" =           "grey75" ,
"Cladosporium" =            "grey75" ,  ##FIXX###
 "Clavispora" =          "rosybrown" ,
  "Cutaneotrichosporon" =                   "grey75",          
 "Cyberlindnera" =             "mistyrose2" ,  
"Cyphellophora" =             "mintcream"   , 
"Cystobasidium" =             "white"    ,    
"Cystofilobasidium" =                 "gold2"    ,         
 "Debaryomyces"   =              "grey75",
"Dictyosporiaceae_gen_Incertae_sedis" = "darkolivegreen1"        ,            
"Didymella" =         "grey75"  ,
 "Exophiala"  = "grey75",
 "Filobasidium" =            "plum" ,       
"Fusarium" =        "grey75",
 "Fusicolla" =         "cornsilk2",
 "Geotrichum" =          "purple4"  , 
 "Galactomyces" = "darksalmon",
 "Geotrichum/Galactomyces" = "seagreen",
 "Hanseniaspora (Kloechera)"= "violetred",
 "Kluyveromyces" =             "cadetblue" ,   
 "Knufia" =      "wheat2",
 "Mucor"      =  "dodgerblue3",
"Naganishia"  =   "grey75",
"Neoascochyta" = "lightpink2",
"None" = "grey4",
"Paecilomyces" = "ivory",
"Other" =      "grey38"   ,
 "Penicillium " =          "springgreen" ,
 "Penicillium" =          "springgreen" ,
 "Pichia" =      "navy",
  "Rhodosporidiobolus" =                  "thistle4",
  "Rhizopus" = "grey75",
"Rhodotorula" =           "grey16",     
 "Rozellomycota_gen_Incertae_sedis" = "lemonchiffon",                    
 "Saccharomyces"  =              "paleturquoise1",
"Saccharomycetales_fam_Incertae_sedis_g__" = "grey50",  
"Sarocladium" = "grey75",
  "Sporobolomyces" = "lemonchiffon2",
"Symmetrospora"  =             "lightgoldenrod",
 "Torulaspora" =           "slateblue1", 
"Vishniacozyma" =             "grey75",   
  "Yarrowia"   =          "violet")



bar1<- ggplot(fac1, aes(x=(Relative.Abundance), y=reorder(Genera, -Relative.Abundance), fill=Genera)) + 
geom_bar(stat = "identity")+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), #Remove background
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
theme(text = element_text(size=40,colour="black",face="bold"), 
       axis.text.x = element_text(angle=0, hjust = 1, colour = 'black',margin=unit(c(0.5,0.5,0.5,0.5), "cm")),
     axis.text.y = element_text(angle = 0, hjust = 1, colour = 'black',margin=unit(c(0.5,0.5,0.5,0.5), "cm")),
     axis.ticks.length = unit(-0.25, "cm"), #-0.25 (inside)
     plot.title= element_text(hjust = 0.9))+
  
    scale_y_discrete(expand = c(0, 0))+
  scale_x_continuous(expand = c(0, 0), limits = c(0,22))+ #Force axis to start at 0 
  #ggtitle((name))+
   ylab(expression(bold("Genus")))+ #change y label
  xlab(expression(bold("Relative Abundance (%)")))+
    scale_fill_manual(values=color_col)+
   #xlim(0, 20)+
  theme(axis.ticks.x = element_blank())# Remove x axis tick marks
#  coord_flip() # rotate plot 

print(bar1)

#Export plot to .tif file 
tiff(paste( "Mean Compositional Abundance Genus Fac1_overlap.tif", sep=" "), res=300, compression = "lzw", height=9, width=18, units="in")
print(bar1)
dev.off()

pdf(paste("Mean Compositional Abundance Genus Fac1 Fac1 _overlap.pdf", sep=" "), height=9, width=15)
print(bar1)
dev.off()



###############################################
#Facility 2
fac2<- read.csv("Fac2_genera.csv")
head(fac2)
fac2$Genera<- as.factor(fac2$Genera)
fac2$Rel_abun<- as.numeric(fac2$Rel_abun)*100
fac2

#custo color
color_col<- c(

"Alternaria" =          "grey75" ,
 "Apiotrichum" =           "grey75"  ,     
 "Aspergillus" =           "grey75" ,    
"Aureobasidium" =             "grey75"  ,   
"Botryotinia" = "lemonchiffon",
"Bullera" = "aliceblue",
"Candida"  =        "red",
"Chordomyces" =           "grey75" ,
"Cladosporium" =            "grey75" ,  ##FIXX###
 "Clavispora" =          "rosybrown" ,
  "Cutaneotrichosporon" =                   "grey75",          
 "Cyberlindnera" =             "mistyrose2" ,  
"Cyphellophora" =             "mintcream"   , 
"Cystobasidium" =             "white"    ,    
"Cystofilobasidium" =                 "gold2"    ,         
 "Debaryomyces"   =              "grey75",
"Dictyosporiaceae_gen_Incertae_sedis" = "darkolivegreen1"        ,            
"Didymella" =         "grey75"  ,
 "Exophiala"  = "grey75",
 "Filobasidium" =            "plum" ,       
"Fusarium" =        "grey75",
 "Fusicolla" =         "cornsilk2",
 "Geotrichum" =          "purple4"  , 
 "Galactomyces" = "darksalmon",
 "Geotrichum/Galactomyces" = "seagreen",
 "Hanseniaspora (Kloechera)"= "violetred",
 "Kluyveromyces" =             "cadetblue" ,   
 "Knufia" =      "wheat2",
 "Mucor"      =  "dodgerblue3",
"Naganishia"  =   "grey75",
"Neoascochyta" = "lightpink2",
"None" = "grey4",
"Paecilomyces" = "ivory",
"Other" =      "grey38"   ,
 "Penicillium " =          "springgreen" ,
 "Penicillium" =          "springgreen" ,
 "Pichia" =      "navy",
  "Rhodosporidiobolus" =                  "thistle4",
  "Rhizopus" = "grey75",
"Rhodotorula" =           "grey16",     
 "Rozellomycota_gen_Incertae_sedis" = "lemonchiffon",                    
 "Saccharomyces"  =              "paleturquoise1",
"Saccharomycetales_fam_Incertae_sedis_g__" = "grey50",  
"Sarocladium" = "grey75",
  "Sporobolomyces" = "lemonchiffon2",
"Symmetrospora"  =             "lightgoldenrod",
 "Torulaspora" =           "slateblue1", 
"Vishniacozyma" =             "grey75",   
  "Yarrowia"   =          "violet")


bar2<- ggplot(fac2, aes(x=(Rel_abun), y=reorder(Genera, -Rel_abun), fill=Genera)) + 
geom_bar(stat = "identity")+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), #Remove background
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
theme(text = element_text(size=40,colour="black",face="bold"), 
       axis.text.x = element_text(angle=0,hjust = 1, colour = 'black',margin=unit(c(0.5,0.5,0.5,0.5), "cm")),
     axis.text.y = element_text(angle = 0, hjust = 1, colour = 'black',margin=unit(c(0.5,0.5,0.5,0.5), "cm")),
     axis.ticks.length = unit(-0.25, "cm"), #-0.25 (inside)
     plot.title= element_text(hjust = 0.9))+
  
    scale_y_discrete(expand = c(0, 0))+
  scale_x_continuous(expand = c(0, 0), limits = c(0,22))+ #Force axis to start at 0 
  #ggtitle((name))+
   ylab(expression(bold("Genus")))+ #change y label
  xlab(expression(bold("Relative Abundance (%)")))+
    scale_fill_manual(values=color_col)+
   #xlim(0, 20)+
  theme(axis.ticks.x = element_blank())# Remove x axis tick marks
#  coord_flip() # rotate plot 

print(bar2)

#Export plot to .tif file 
tiff(paste("Mean Compositional Abundance Genus Fac2 overlap.tif", sep=" "), res=300, compression = "lzw", height=9, width=18, units="in")
print(bar2)
dev.off()

pdf(paste("Mean Compositional Abundance Genus Fac2 overlap.pdf", sep=" "), height=9, width=18)
print(bar2)
dev.off()


###############################
#Facility 3
fac3<- read.csv("Fac3_genera.csv")
head(fac3)
fac3$Genera<- as.factor(fac3$Genera)
fac3$Rel_abun<- as.numeric(fac3$Rel_abun)*100
fac3


color_col<- c(

"Alternaria" =          "grey75" ,
 "Apiotrichum" =           "grey75"  ,     
 "Aspergillus" =           "grey75" ,    
"Aureobasidium" =             "peachpuff"  ,   
"Botryotinia" = "lemonchiffon",
"Bullera" = "aliceblue",
"Candida"  =        "red",
"Chordomyces" =           "grey75" ,
"Cladosporium" =            "darkgreen" ,  ##FIXX###
 "Clavispora" =          "rosybrown" ,
  "Cutaneotrichosporon" =                   "grey75",          
 "Cyberlindnera" =             "mistyrose2" ,  
"Cyphellophora" =             "mintcream"   , 
"Cystobasidium" =             "white"    ,    
"Cystofilobasidium" =                 "gold2"    ,         
 "Debaryomyces"   =              "grey75",
"Dictyosporiaceae_gen_Incertae_sedis" = "darkolivegreen1"        ,            
"Didymella" =         "grey75"  ,
"Didymellaceae_g__" =                 "hotpink"   ,      
 "Exophiala"  = "grey75",
 "Filobasidium" =            "plum" ,       
"Fusarium" =        "grey75",
 "Fusicolla" =         "cornsilk2",
 "Geotrichum" =          "purple4"  , 
 "Galactomyces" = "darksalmon",
 "Geotrichum/Galactomyces" = "seagreen",
 "Hanseniaspora (Kloechera)"= "violetred",
 "Humicola"   =          "indianred3",
 "Iodophanus" =          "slateblue4",
 "Kluyveromyces" =             "cadetblue" ,   
 "Knufia" =      "wheat2",
 "Kurtzmaniella" =             "olivedrab1" ,  
"Leucosporidium" =              "yellowgreen",   
 "Malassezia" =         "lightpink4",
"Meyerozyma" =         "violetred4",
 "Mrakia" =     "sienna",
 "Mucor"      =  "dodgerblue3",
"Naganishia"  =   "grey75",
"Neoascochyta" = "lightpink2",
"None" = "grey4",
"Paecilomyces" = "ivory",
 "Ophiostoma" =          "seashell4" ,
"Orbilia" =      "gold"   ,
"Other" =      "grey38"   ,
 "Papiliotrema"   =              "mediumseagreen",
 "Penicillium " =          "springgreen" ,
 "Penicillium" =          "springgreen" ,
"Phlebiopsis"  =            "springgreen2",
 "Pichia" =      "navy",
 "Piskurozyma" =           "firebrick1" ,
 "Preussia"   =          "violetred2",
 "Proceropycnis" =             "seashell2",    
 "Rhodosporidiobolus" =                  "thistle4",
  "Rhizopus" = "grey75",
"Rhodotorula" =           "grey16",     
 "Rozellomycota_gen_Incertae_sedis" = "lemonchiffon",                    
 "Saccharomyces"  =              "paleturquoise1",
"Saccharomycetales_fam_Incertae_sedis_g__" = "grey50",  
"Sarocladium" = "grey75",
  "Sporobolomyces" = "lemonchiffon2",
"Symmetrospora"  =             "lightgoldenrod",
 "Talaromyces" =           "violet",     
"Tausonia"    =           "dodgerblue1",
 "Tetracladium" =            "ivory2",   
 "Torulaspora" =           "slateblue1", 
"Trichoderma" =           "grey80",     
"Trichosporon" =           "forestgreen",
"Trametes" = "grey68",
"Vishniacozyma" =             "grey75",   
  "Yarrowia"   =          "violet")



bar3<- ggplot(fac3, aes(x=(Rel_abun), y=reorder(Genera, -Rel_abun), fill=Genera)) + 
geom_bar(stat = "identity")+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), #Remove background
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
theme(text = element_text(size=40,colour="black",face="bold"), 
       axis.text.x = element_text(angle=0,hjust = 1, colour = 'black',margin=unit(c(0.5,0.5,0.5,0.5), "cm")),
     axis.text.y = element_text(angle = 0, hjust = 1, colour = 'black',margin=unit(c(0.5,0.5,0.5,0.5), "cm")),
     axis.ticks.length = unit(-0.25, "cm"), #-0.25 (inside)
     plot.title= element_text(hjust = 0.9))+
  
    scale_y_discrete(expand = c(0, 0))+
  scale_x_continuous(expand = c(0, 0), limits = c(0,22))+ #Force axis to start at 0 
  #ggtitle((name))+
   ylab(expression(bold("Genus")))+ #change y label
  xlab(expression(bold("Relative Abundance (%)")))+
    scale_fill_manual(values=color_col)+
   #xlim(0, 20)+
  theme(axis.ticks.x = element_blank())# Remove x axis tick marks
#  coord_flip() # rotate plot 

print(bar3)

#Export plot to .tif file 
tiff(paste( "Mean Compositional Abundance Genus Fac3 overlap.tif", sep=" "), res=300, compression = "lzw", height=9, width=18, units="in")
print(bar3)
dev.off()

pdf(paste("Mean Compositional Abundance Genus Fac3 overlap.pdf", sep=" "), height=9, width=18)
print(bar3)
dev.off()


```
